config/routes.rb
Rails.application.routes.draw do
  resources :products

  resource :cart, only: [ :show ] do # note: resource is singular, not plural.
    post "add", path: "add/:id", on: :member # post means create, it works on member
  end

  root 'products#index'

end

app/models/cart.rb
class Cart

  attr_reader :items

  # transforming from hash to a series of cart items.
  def self.build_from_hash hash # pass a hash
    items = if hash["cart"] then # if cart exists then we go inside hash -> cart -> items otherwise return an empty array
      # this hash represents a session, and we want to check if there is a cart in this session/hash
      hash["cart"]["items"].map do |item_data|
        CartItem.new item_data["product_id"], item_data["quantity"]
      end
    else
      []
    end
    new items # at the very end of it, build a new instance of cart
  end

  def initialize items = [] # set the items as an empty array
    @items = items # pass items as the array of items
  end

  def add_item product_id
    # The reason we are adding product_id, not adding a product object, is because the session variable doesn't hold on data: object,
    # but rather on the primitive classes such as numbers, arrays, strings and hashes.
    item = @items.find { |item| item.product_id == product_id } # search if that product_id is already in the items arrays
    if item # if found
      item.increment
    else
      @items << CartItem.new(product_id) # quantity by default is 1 for new CartItem object
    end
  end

  def empty?
    @items.empty?
  end

  def count
    @items.length
  end

  def serialize # we are serializing the contents of the cart into a hash
    items = @items.map do |item|
      {
        "product_id" => item.product_id,
        "quantity" => item.quantity
      }
    end

    # {
    #   "cart" => {
    #     "items" => items
    #   }
    # } ## after modification in the add method, instead of passing a cart,
    ## I will pass a list of items, see below:

    {
      "items" => items
    }
  end
  # test the other way around, we want to get the cart objects from the session hash


  def total_price
    @items.inject(0) { |sum, item| sum + item.total_price }
    # zero will be added first to the item.total_price and so on
  end
end

app/models/cart_item.rb
class CartItem
  attr_reader :product_id, :quantity

  def initialize product_id, quantity = 1 # quantity is 1 if nothing is defined
    @product_id = product_id
    @quantity = quantity
  end

  def increment
    @quantity = @quantity + 1
  end

  def product
    Product.find product_id # Product is from the class Product.
    # product_id exists because we have an attr_reader :product_id
  end

  def total_price
    product.price * quantity  
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  mount_uploader :image, ImageUploader

  validates_presence_of :name, :price
  validates_numericality_of :price # to ensure price should be a number
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # use ApplicationController to store a cart
  def initialize_cart
    @cart = Cart.build_from_hash session # session variable always exists in each controller
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_filter :initialize_cart

  # we don't want to have cart template, rather, we want it to redirect_to the previous page
  def add
    @cart.add_item params[:id]
    # we need to pass serialize method to the session variable
    ## session = @cart.serialize # DANGEROUS METHOD: DO NOT USE - it's because we do not want to override the session variable
    # rather we want to make sure that the "cart" variable is the result of serialize method
    session["cart"] = @cart.serialize # must update serialize method in the model
    # its like ["cart"] = items hash, items are part of the cart.
    # if we pass cart as a session as the first way above, that's DANGEROUS because there are other variables that might be deleted if
    # we do like the first way above
    product = Product.find params[:id]
    redirect_to :back, notice: "Added #{product.name} to cart."
  end

  def show
    
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_filter :initialize_cart
  
  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/application/_cart.html.haml
-# if a cart exists and it's not empty, then render the text
-if @cart
  %p.navbar-text.navbar-right
    -if @cart.empty?
      Your cart is empty.
    -else
      =link_to "You have #{pluralize @cart.count, "item"}.", cart_path

app/views/application/_nav.html.erb
<%# source http://getbootstrap.com/components/#navbar %>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Kathy Office Supplies</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to "Products", products_path %></li>
      </ul>
      <%= render "cart" %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/carts/show.html.haml
%table.table.table-hover
  %thead
    %tr
      %th Quantity
      %th Product
      %th Price

  -@cart.items.each do |item|
    %tr
      %td=item.quantity
      %td
        =cl_image_tag item.product.image_url, size: "50"
        =link_to item.product.name, item.product
      %td=item.total_price

%p=number_to_currency @cart.total_price

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsStore</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'nav'%>
<div class='container'>
  <%= content_tag :div, notice, class: "bg-success" %>
  <%= content_tag :div, alert, class: "bg-danger" %>
  <%= yield %>
</div>
</body>
</html>

app/views/products/_form.html.haml
= form_for @product, multipart: true do |f|
  - if @product.errors.any?
    #error_explanation
      %h2= "#{pluralize(@product.errors.count, "error")} prohibited this product from being saved:"
      %ul
        - @product.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :price
    = f.text_field :price
  .field
    = f.label :image
    = f.file_field :image #changed from text_field to file_field to store image
  .actions
    = f.submit 'Save'

app/views/products/edit.html.haml
%h1 Editing product

= render 'form'

= link_to 'Show', @product
\|
= link_to 'Back', products_path

app/views/products/index.html.haml
%h1 Listing products

%table.table.table-hover
  %thead
    %tr
      %th Name
      %th Price
      %th Image
      %th

  %tbody
    - @products.each do |product|
      %tr
        %td= link_to product.name, product
        %td= number_to_currency product.price
        %td= cl_image_tag product.image_url, size: "100"
        %td
          = link_to 'Edit', edit_product_path(product)
          = link_to 'Destroy', product, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Product', new_product_path, class: "btn btn-primary"

app/views/products/new.html.haml
%h1 New product

= render 'form'

= link_to 'Back', products_path

app/views/products/show.html.haml
%p#notice= notice
%h1= @product.name
%p= number_to_currency @product.price
%p= cl_image_tag(@product.image_url, height: "300")

%p= link_to "Add to Cart", add_cart_path, method: :post, class: "btn btn-primary"

= link_to 'Edit', edit_product_path(@product)
\|
= link_to 'Back', products_path